apiVersion: v2
name: mzc-cloudops-v2
description: CloudOps v2 Umbrella Helm Chart
type: application
version: 0.1.7
appVersion: "0.1.7"

dependencies:
  - name: core
    version: "0.1.7"
    repository: oci://ghcr.io/mzc-cloudops-v2/charts
    condition: core.enabled
  - name: plugin-aws-resource-collector
    version: "0.1.1"
    repository: oci://ghcr.io/mzc-cloudops-v2/charts
    condition: plugin-aws-resource-collector.enabled
